import { Resend } from "resend";

const resendApiKey = process.env.RESEND_API_KEY;
// Determine if a valid API key is present (not empty and not the placeholder template)
const isValidKey = resendApiKey && resendApiKey !== "re_your_resend_api_key";

export const resend = isValidKey ? new Resend(resendApiKey) : null;

/**
 * Dispatches an HTML email alert to the system administrator when a new enquiry is registered.
 * Fails gracefully (logged warning) if Resend is unconfigured.
 */
export async function sendAdminEnquiryNotification({ propertyTitle, name, email, phone, message }) {
  if (!resend) {
    console.warn("Resend API Key is not configured. Email notification skipped.");
    return null;
  }

  const adminEmail = process.env.ADMIN_EMAIL || "admin@propertylisting.com";
  const fromEmail = process.env.RESEND_FROM_EMAIL || "onboarding@resend.dev";

  try {
    const data = await resend.emails.send({
      from: `LuxeEstates Alerts <${fromEmail}>`,
      to: adminEmail,
      subject: `New Property Enquiry: ${propertyTitle}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e5e7eb; rounded: 12px; color: #1f2937;">
          <h2 style="color: #4f46e5; border-bottom: 2px solid #f3f4f6; padding-bottom: 10px; margin-bottom: 20px;">
            New Lead Captured
          </h2>
          
          <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
            <tr>
              <td style="padding: 6px 0; font-weight: bold; color: #4b5563; width: 140px;">Property:</td>
              <td style="padding: 6px 0; font-weight: 800; color: #111827;">${propertyTitle}</td>
            </tr>
            <tr>
              <td style="padding: 6px 0; font-weight: bold; color: #4b5563;">Customer Name:</td>
              <td style="padding: 6px 0; color: #111827;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 6px 0; font-weight: bold; color: #4b5563;">Email Address:</td>
              <td style="padding: 6px 0; color: #111827;"><a href="mailto:${email}">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 6px 0; font-weight: bold; color: #4b5563;">Phone Number:</td>
              <td style="padding: 6px 0; color: #111827;"><a href="tel:${phone}">${phone}</a></td>
            </tr>
          </table>

          <div style="background-color: #f9fafb; padding: 16px; border-left: 4px solid #4f46e5; border-radius: 8px; font-size: 14px; line-height: 1.6; color: #374151;">
            <p style="margin-top: 0; font-weight: bold; color: #4f46e5;">Submitted Message:</p>
            <p style="margin-bottom: 0; white-space: pre-wrap;">${message}</p>
          </div>
          
          <div style="margin-top: 24px; text-align: center; border-top: 1px solid #f3f4f6; padding-top: 16px; font-size: 11px; color: #9ca3af;">
            This alert was automatically generated by LuxeEstates Portal.
          </div>
        </div>
      `,
    });
    return data;
  } catch (error) {
    console.error("Resend API request failed:", error);
    return null; // Return null to indicate failure, allowing the caller to proceed
  }
}
